# Generated by Django 3.1.4 on 2020-12-05 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_title_id', models.CharField(max_length=64, unique=True)),
                ('original_title', models.CharField(max_length=128)),
                ('year', models.IntegerField(null=True)),
                ('date_published', models.DateField(null=True)),
                ('duration', models.IntegerField(null=True)),
                ('country', models.CharField(max_length=128, null=True)),
                ('director', models.CharField(max_length=128, null=True)),
                ('production_company', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovieVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_imdb_id', models.CharField(max_length=128)),
                ('user_key', models.CharField(max_length=16)),
                ('rating', models.PositiveSmallIntegerField()),
                ('movie', models.ForeignKey(max_length=128, on_delete=django.db.models.deletion.PROTECT, to='recommender.movie')),
            ],
        ),
    ]
