# Generated by Django 3.1.4 on 2020-12-06 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_auto_20201205_0415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movievote',
            name='movie',
        ),
    ]
