# Generated by Django 3.1.4 on 2020-12-06 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0003_remove_movievote_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movievote',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='recommender.movie'),
        ),
        migrations.AlterField(
            model_name='movievote',
            name='rating',
            field=models.SmallIntegerField(),
        ),
    ]
